# Generated by Django 5.2.17 on 2026-09-29 16:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('classification', models.CharField(max_length=32)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('dry_run', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.sourcebook')),
            ],
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=80)),
                ('row', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(max_length=64)),
                ('detail', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rutas.importrun')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('part_type', models.CharField(blank=True, max_length=16)),
                ('bom_revision', models.CharField(blank=True, max_length=80)),
                ('drawing_revision', models.CharField(blank=True, max_length=80)),
                ('drawing_number', models.CharField(blank=True, max_length=160)),
                ('od_raw', models.CharField(blank=True, max_length=80)),
                ('wall_raw', models.CharField(blank=True, max_length=80)),
                ('development_raw', models.CharField(blank=True, max_length=80)),
                ('development_formula', models.CharField(blank=True, max_length=160)),
                ('comments', models.TextField(blank=True)),
                ('phase', models.CharField(blank=True, max_length=80)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_values', models.JSONField(default=dict)),
                ('needs_review', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.client')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.sourcebook')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, max_length=32)),
                ('revision', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('review', 'Por revisar'), ('active', 'Activa'), ('archived', 'Archivada')], default='review', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_sheet', models.CharField(blank=True, max_length=80)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_code', models.CharField(blank=True, max_length=160)),
                ('source_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.client')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.part')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.sourcebook')),
            ],
        ),
        migrations.CreateModel(
            name='RouteChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=32)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rutas.route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=40)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('planner', models.CharField(blank=True, max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('template_key', models.CharField(max_length=80)),
                ('snapshot', models.JSONField()),
                ('pdf', models.FileField(upload_to='documents/%Y/%m')),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_order', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('position', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rutas.schedule')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveIntegerField()),
                ('source_raw_quantity', models.CharField(blank=True, max_length=80)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='rutas.part')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='rutas.part')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'position'), name='unique_bom_position')],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('source_sequence', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('tooling', models.TextField(blank=True)),
                ('inspection', models.TextField(blank=True)),
                ('machine', models.TextField(blank=True)),
                ('source_group', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='rutas.route')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('route', 'position'), name='unique_operation_position')],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['client', 'code'], name='rutas_route_client__a40296_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status', 'code'], name='rutas_route_status_750ade_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'source_sheet', 'source_row'), name='unique_route_origin'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['client', 'code'], name='rutas_part_client__0519e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('source', 'source_row'), name='unique_part_origin'),
        ),
    ]
