# Generated by Django 5.2.17 on 2026-09-29 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_importissue_resolution_note_importissue_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
