# Generated by Django 5.2.17 on 2026-09-29 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_schedule_issue_date_schedule_ship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='copies',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
