# Generated by Django 5.2.17 on 2026-10-06 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_part_quantity_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversoPart',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=160)),
                ('normalized_number', models.CharField(db_index=True, max_length=160)),
                ('customer', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['part_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UniversoSync',
            fields=[
                ('key', models.CharField(default='catalog', max_length=16, primary_key=True, serialize=False)),
                ('cursor', models.TextField(blank=True)),
                ('initialized', models.BooleanField(default=False)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('lease', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='universe_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='rutas.universopart'),
        ),
    ]
