# Generated by Django 5.2.17 on 2026-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_universopart_universosync_route_universe_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='universe_auto_link',
            field=models.BooleanField(default=True),
        ),
    ]
